Attempted to recreate environment and put in yml
wumphlett/ML-Project pull request #2
Opened 2022-11-03 19:25 UTC by MatthewFreestone

Using the existing env yaml, I was not able to get all of the required packages in one step. This update should make that happen

2022-11-03 22:19 UTC, wumphlett commented
I think the prefix line with your specific file path should be removed

2022-11-03 23:18 UTC, wumphlett requested changes

2022-11-03 23:18 UTC, wumphlett commented on environment.yml
> +prefix: C:\Users\matth\anaconda3\envs\ml-project
Should this line be removed?

2022-11-04 01:20 UTC, MatthewFreestone commented on environment.yml
> +prefix: C:\Users\matth\anaconda3\envs\ml-project
Yep -- good call! I'll remove it

2022-11-04 14:03 UTC, merged